// header
#include<fstream.h>
#include<conio.h>
#include<stdlib.h>
#include<stdio.h>
#include<string.h>
#include<iomanip.h>
#include<dos.h>
#include<graphics.h>
void menu();
#include"c:\turboc3\bin\file\invent\sound.cpp"
#include"c:\turboc3\bin\file\invent\display.cpp"
#include"c:\turboc3\bin\file\invent\password.cpp"
#include"c:\turboc3\bin\file\invent\Number.cpp"
#include "c:\TurboC3\BIN\file\invent\class.cpp"
#include "c:\TurboC3\BIN\file\invent\add.cpp"
#include "c:\TurboC3\BIN\file\invent\show.cpp"
#include"c:\turboc3\bin\file\invent\delete.cpp"
#include "c:\TurboC3\BIN\file\invent\modify.cpp"
#include "c:\Turboc3\bin\file\invent\reorder.cpp"
#include "c:\TurboC3\BIN\file\invent\bill.cpp"
#include "c:\TurboC3\BIN\file\invent\purchase.cpp"
#include "c:\Turboc3\bin\file\invent\backup.cpp"
#include "c:\TurboC3\BIN\file\invent\admin.cpp"
#include "c:\TurboC3\BIN\file\invent\customer.cpp"
#include "c:\TurboC3\BIN\file\invent\menu.cpp"



